### ISSUE TITLE
In v2.0.1, passing row number 0 with R1C1 notation causes an infinite loop and eventual memory error

### ISSUE THREAD

**Issue by robinbullocks4rb** [mike182uk/cellref#18]
```javascript
const cellref = require('cellref');
cellref('R1C0');
```

In 2.0.0, this would return `'@1'`. In 2.0.1, the call never returns and eventually the process runs out of memory.

```
<--- Last few GCs --->

[13376:0x102801600]    13885 ms: Mark-sweep 1399.6 (1430.0) -> 1399.6 (1430.0) MB, 612.0 / 0.0 ms  allocation failure GC in old space requested
[13376:0x102801600]    14619 ms: Mark-sweep 1399.6 (1430.0) -> 1399.6 (1429.0) MB, 616.7 / 0.0 ms  last resort gc 
[13376:0x102801600]    15350 ms: Mark-sweep 1399.6 (1429.0) -> 1399.6 (1429.0) MB, 730.7 / 0.0 ms  last resort gc 


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x258c04bc0d31 <JS Object>
    2: convertR1C1toA1 [<redacted>/node_modules/cellref/index.js:~81] [pc=0x3abc392b047c](this=0x258c04bd3259 <JS Global Object>,ref=0x258c04b04311 <undefined>)
    3: cellref [<redacted>/node_modules/cellref/index.js:35] [pc=0x3abc3929f772](this=0x258c04bd3259 <JS Global Object>,ref=0x2aadc4c4a0b1 <String[4]: R1C0>)
    4: /* anonymous */ [repl:1] [pc=0x3abc392aac...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/robin/.nvm/versions/node/v7.0.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/robin/.nvm/versions/node/v7.0.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/robin/.nvm/versions/node/v7.0.0/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/Users/robin/.nvm/versions/node/v7.0.0/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/robin/.nvm/versions/node/v7.0.0/bin/node]
 6: 0x3abc39108506
Abort trap: 6

**Comment by robinbullocks4rb** [comment]
I'm happy to attempt a PR for this, but I'm unsure what the correct behaviour should be. Should it continue to return `@1` (not sure what the `@` symbolises) or should it throw the `could not detect cell reference notation...` error?

**Comment by mike182uk** [comment]
Hey @robinbullocks4rb,

Wouldn't `R1C0` actually be invalid because there is no column 0? or do you have a use case for using `R1C0`?

**Comment by robinbullocks4rb** [comment]
Hi @mike182uk, yeah, I agree it would be invalid - apologies, I should have been more explicit that I saw it as an error case, I just wasn't sure if I should throw the error in that situation or do something else.

We don't have a valid use-case as such, turns out one of our tests was passing that argument in error but took me a while to track it down, so I just wanted to change something to stop this exact situation re-occurring.

**Comment by mike182uk** [comment]
Ah cool no worries, thanks for raising the issue!

Im wondering if it would be enough to just update the Regex to not match on letters followed by zeros - in that case you would see an error message saying the cell reference is not valid

**Comment by robinbullocks4rb** [comment]
I agree; I'll construct a PR.
